api-platform/api-doc-parser

- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
At the moment it is impossible to pass any kind of custom headers to the requests fetching the docs.
One valid use case would be parsing a documentation requiring an authentication.
> Allow options to be passed down to inner fetches

- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
Hi there,
I once experienced the same issue as @vitalyiegorov in dunglas/api-doc-parser#6 (also api-platform/admin#8).
This is caused by an `undefined` `range` for a property:
```
{
"@type": "hydra:SupportedProperty",
"hydra:property": {
"@id": "#CustomResource/sanitizedDescription",
"@type": "rdf:Property",
"rdfs:label": "sanitizedDescription",
"domain": "#CustomResource"
},
"hydra:title": "sanitizedDescription",
"hydra:required": false,
"hydra:readable": true,
"hydra:writable": false
}
```
Regarding [api-platform/core](https://github.com/api-platform/core), you can stumble on this when defining a custom `getter` which is not directly correlated with a class property name. This happens when attempting to map PHP types to Json-ld types. 
This is directly linked to the …
> Prevent doc parsing failure when the range attribute is not present on a property

- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
I want to add some additional methods in `api` (as indicated in [api-platform/admin](https://github.com/api-platform/admin/blob/master/src/fieldFactory.js#L33)).
Unfortunately, it is not always possible to determine if these methods have to be added in `writableFields` or in `readableFields`. For example `GET_ONE` event is used by `Show` and by `Edit`.
To solve this problem, I added an attribute `fields`: this attribute contains all fields of the resource (regardless of the writability / readability).
> Add attribute "fields" in Resource

- README.md
- package.json
- src/Api.js
- src/hydra/fetchJsonLd.js
- src/hydra/fetchJsonLd.test.js
- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
I added properties `response` and `status` to `Api`.
If [response.ok](https://developer.mozilla.org/fr/docs/Web/API/Response/ok) is:
* `false`, the `fetch` promise will be rejected.
* `true`, the original behaviors is kept.
In all cases:
* the `response` will be returned (see `src/hydra/fetchJsonLd.json`).
* an instance of `Api` instance will be created and the returned `response` will be injected (see `src/hydra/parseHydraDocumentation.json`).
---
With this PR, we can now handle fetch error (should fix issue #12).
> Handle "fetch" error

- src/hydra/fetchJsonLd.js
- src/hydra/fetchJsonLd.test.js
From an instance of `api-platform/admin`, I try to delete a resource but I have got an error.
The API response is correct (`204 - No Content`) but `fetchJsonLd` checks if the `Content-Type` is valid. Unfortunately, with `symfony`, an empty response has `text/html` as `Content-Type` value.
In this PR, I added a condition for `204` responses.
> Fix the possibility to fetch an empty document

- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
It allows the parser to work even when read-only classes are exposed.
> Use owl:equivalentClass when available

- src/hydra/fetchJsonLd.js
- src/hydra/fetchJsonLd.test.js
In my previous commit, I added the possibility to reject promise if the response is incorrect. With the  possibility, it was possible to manage authentication.
Unfortunately my commit brokes validations: when `fetchJsonLd` retrieve a `4XX` response, it will reject the promise but in [fetchHydra](https://github.com/api-platform/admin/blob/master/src/hydra/fetchHydra.js#L30), we analyse only resolved promise.
To solve issue [api-platform/admin#68](https://github.com/api-platform/admin/issues/68), I propose to:
* reject only `5XX` errors or non valid response (same behaviors as `fetch`).
* the `4XX` responses will be resolved but parsing will fail so the promise will be reject (no change for `api-platform/admin`).
> Reject only 5XX errors

- package.json
- src/Parameter.js
- src/Resource.js
- src/hydra/addParameters.js
- src/hydra/fetchResource.js
- src/hydra/parseHydraDocumentation.js
- src/hydra/parseHydraDocumentation.test.js
In parseHydraDocumentation > addFilters
I made the choice to ignore filters with _null_ property (PropertyFilter provides _null_).
Are you ok with this ?
> Filters implementation

- package.json
> Add a watch script

- src/hydra/getParameters.js
To avoid making the `getParameters` request several times, update `resource.parameters` with the `fetch`'s return.
This PR is related to https://github.com/coopTilleuls/admin/pull/10
> RFR - Set resource.parameters from query

- README.md
- package.json
- src/openapi3/handleJson.js
- src/openapi3/handleJson.test.js
- src/openapi3/index.js
- src/openapi3/parseOpenApi3Documentation.js
This PR adds a parser for OpenAPI v3.
@dunglas Can you please review?
> Add support for OpenAPI v3.

- src/Resource.ts
- src/hydra/parseHydraDocumentation.test.ts
- src/hydra/parseHydraDocumentation.ts
API Platform version(s) affected: any
Description
There has never been hydra:writable in the Hydra spec.
How to reproduce
N/A
Additional Context
N/A
PR done on the core repository too : https://github.com/api-platform/core/pull/3481
> Fix: hydra:writable to  hydra:writeable

- src/Field.ts
- src/hydra/parseHydraDocumentation.test.ts
- src/hydra/parseHydraDocumentation.ts
| Bug fix?      | yes
| New feature?  | yes
| Tickets       | N/A
| Doc PR        | N/A
The parser was not able to tell the difference between a reference relation (IRI) and an embedded relation.
No it can thanks to a new `embedded` field.
Sadly it cannot tell which fields exactly are embedded since the Hydra documentation doesn't specify it (could it do it?).
> Add embedded support

- src/hydra/parseHydraDocumentation.test.ts
- src/hydra/parseHydraDocumentation.ts
| Bug fix?      | yes
| New feature?  | no
| Tickets       | N/A
| Doc PR        | N/A
Following https://github.com/api-platform/api-doc-parser/pull/78.
Allow `writable` to not break everything...
> Allow writable in Hydra

- src/hydra/fetchResource.ts
Override is useless and lead to complex `checkError()` behavior, `fetchJsonLd` already throw `{ resource }` object
| Bug fix?      | yes
| New feature?  | no
| Tickets       | no
| Doc PR        | no
`fetchResource` should not override default `fetchJsonLd` throwed error to have a consistent `checkError()` on `react-admin`
> Remove fetchResource 'Unreachable resource' error override

- .eslintrc.js
- src/hydra/fetchJsonLd.ts
- src/hydra/fetchResource.ts
- src/hydra/getParameters.ts
- src/hydra/parseHydraDocumentation.test.ts
- src/hydra/parseHydraDocumentation.ts
- src/hydra/types.ts
- tsconfig.eslint.json
- tsconfig.json
Allow users to give a function for `headers` key in `parseHydraDocumentation` options
| Bug fix?      | no
| New feature?  | yes
| Tickets       | no
| Doc PR        | no
Else, on an authenticated `react-admin` application using a `JWT`, when this one is `expired` you're logged out, once `logged` again, the first request still use old configured `headers`
> Add function headers behavior

- src/hydra/parseHydraDocumentation.ts
| Bug fix?      | no
| New feature?  | no
| Tickets       | N/A
| Doc PR        | N/A
The resource needs to have a GET collection operation to appear in the entrypoint, not an item one.
> Use better error message when the resource is not found in the entrypoint

- README.md
- package.json
- src/openapi3/handleJson.ts
- tsconfig.esm.json
- tsconfig.json
| Branch?       | main
| Bug fix?      |  no
| New feature?  | yes
| Tickets       | /
| Doc PR        |
Hi!
I recently used @api-platform/admin on a project. Great starter for an admin!
I noticed that this library is not tree-shakeable. This means that even if I am not using graphql endpoints, the graphql library will be bundled and downloaded by the users. It is a whopping 43kb gzipped (see https://bundlephobia.com/result?p=graphql@15.0.0)!
I tried to embed both CJS and ESM builds in one package, with scoped exports to allow both node and a browser/webpack to find the correct package. Let me know if I missed something.
I tried a couple of builds: this reduces the gzipped bundled size by around 40kb when …
> Export both ESM and CJS for treeshaking

- .eslintrc.js
- src/hydra/fetchJsonLd.test.ts
- src/hydra/fetchJsonLd.ts
- src/hydra/parseHydraDocumentation.test.ts
- src/hydra/parseHydraDocumentation.ts
- src/swagger/handleJson.ts
| Branch?       | main
| Tickets       | N/A
| Doc PR        | N/A
The behavior of fetchJsonLd when an empty response (204) is received has been changed: instead of resolving the promise, the promise is now rejected.
> fix: use RemoteDocument for fetchJsonLd response

- package.json
- src/openapi3/handleJson.ts
Switching the json-refs dep for two reasons:
- json-refs is not maintained anymore
- json-refs uses Node.js modules (path, querystring...) and Webpack 5 does not polyfill them anymore
Using @apidevtools/json-schema-ref-parser has been considered but [it uses Node.js modules](https://github.com/APIDevTools/json-schema-ref-parser/issues/254) too.
[jsonref](https://github.com/vivocha/jsonref) is not widely used but does not use Node.js modules (and has 0 dependency).
> fix: use jsonref instead of json-refs

- jest.config.ts
- package.json
- tsconfig.esm.json
- tsconfig.json
Since [jsonref](https://github.com/vivocha/jsonref) is already ESM only and more and more packages will be (for instance [graphql](https://github.com/graphql/graphql-js) in version 17), it doesn't make sense to build CJS and it would require to use dynamic imports for the dependencies.
> fix: build only esm

- package.json
- src/hydra/fetchResource.ts
| Branch?       | main
The hydra prefix is now optional and need to not be hardcoded.
> fix(hydra): hydra prefix optional (remove hardcoded values)

- src/hydra/parseHydraDocumentation.ts
We did a pass on fixing a few issues in our hydra implementation at https://github.com/api-platform/core/pull/6748. We're now specifying the `http://www.w3.org/ns/hydra/core#title` instead of the optional and more specific `http://www.w3.org/2000/01/rdf-schema#label` (on `hydra:supportedOperation` and `hydra:supportedProperty`).
> fix: prefer hydra title when available

- .github/workflows/ci.yml
- eslint.config.mjs
- jest.config.ts
- package.json
- pnpm-lock.yaml
- src/hydra/fetchJsonLd.ts
- src/openapi3/parseOpenApi3Documentation.ts
- tsconfig.build.json
- tsconfig.eslint.json
- tsconfig.json
* Re-aligns our **library build and dev setup with the 2025 TypeScript defaults**.  
* Introduces a dedicated **`tsconfig.build.json`**.  
* Switches to **`module: "NodeNext"` and modern ES2022 targets**, giving consumers first-class ESM support and smaller, helper-free output.  
* Enables the compiler options that catch the most common API-breaking mistakes (unused code, fall-through switches, mismatched casing, etc.) without resorting to a bundler.  
* Cleans up redundant or legacy flags, resulting in a clearer config that mirrors community best practices.
* Matt Pocock – TSConfig Cheat Sheet  
https://www.totaltypescript.com/tsconfig-cheat-sheet
* TypeScript Docs – Compiler Options  
https://www.typescriptlang.org/tsconfig
* 2ality – *“Up-to-date tsconfig.json in 2025”* …
> chore: modernize package.json and TypeScript configuration

- pnpm-lock.yaml
- pnpm-workspace.yaml
When trying to contribute, I can't pnpm install on a fresh clone: 
` ERROR  packages field missing or empty`
> fix(config): pnpm workspace
